[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.45"
kelpie-core = { workspace = true }
anyhow = { workspace = true }
zirael_utils = { workspace = true }
log = "0.4.27"