[package]
name = "kelpie-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1"
serde_derive = "1.0.219"
toml = "0.9.5"
anyhow = { workspace = true }
fs-err = { workspace = true }
id-arena = { workspace = true }
zirael_core = { path = "../../zirael/crates/zirael_core" }
glob = "0.3.3"