[package]
name = "test-lib"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tempdir = "0.3.7"
fs-err = { workspace = true }
anyhow = { workspace = true }
zirael_utils = { workspace = true }

[lints]
workspace = true
